### ISSUE TITLE
Fix readthedocs auto build

### ISSUE THREAD

**Issue by AdrianDAlessandro** [CSIRO-Precision-Agriculture/pyprecag#3]
The gdal C libraries are too complex to install for the readthedocs, need to find a way around it.

**Comment by AdrianDAlessandro** [comment]
Attempting telling readthedocs to try a conda install in the [readthedocs_build branch](/github/CSIRO-Precision-Agriculture/pyprecag/tree/readthedocs-build)

**Comment by AdrianDAlessandro** [comment]
Installing gdal with conda worked, but the pyprecag install timed out. Trying with mock imports now.

**Comment by AdrianDAlessandro** [comment]
Either the docs do not build properly, or the build times out. Deciding for the moment to build the docs without the API documentation properly building. Will revisit.

**Comment by andrewspiers** [comment]
Worked around this by having travis build; and github host the documentation instead of using RTD.
